spring.application.name=demo
# Conexión a la base de datos en Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/microapi_db
spring.datasource.username=postgres
spring.datasource.password=secret_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' crea las tablas automáticamente en Docker basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update
# Muestra los comandos SQL reales en la consola de Spring (útil para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true